### ISSUE TITLE
Crash when sending SIGTERM to wget2

### ISSUE THREAD

**Issue by remyabel2** [rockdaboot/wget2#264]
# System info

OS: Fedora 36
wget2 version: 2.0.0

# Command invocation

```
wget2 --no-parent \
    --retry-on-http-error="*,\!404" \
    --save-content-on="*,!404" \
    --continue \
    --reject webm,mov,mkv,mp4 \
    --mirror \
    --convert-links \
    --adjust-extension \
    --page-requisites \
    --wait=1 \
    --waitretry=5 \
    --random-wait \
    --inet4-only \
    --no-cookies \
    --user-agent="" \
    --https-only \
    --https-enforce=hard \
    -nv "$@" -o "$logfile"
```

Then in another script I'm calling wget2 in parallel:

```
parallel -j 10 ./script.sh <list.txt
```

Sending SIGTERM (using CTRL+C) causes wget2 to crash.

# GDB stacktrace

```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `wget2 --no-parent --retry-on-http-error=*,\!404 --save-content-on=*,!404 --cont'.
--Type <RET> for more, q to quit, c to continue without paging--
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
[Current thread is 1 (Thread 0x7f1012a26940 (LWP 56406))]
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f1013304cb3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f10132b49c6 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f101329e7f4 in __GI_abort () at abort.c:79
#4  0x000055a6e7cf0d76 in nop (sig=<optimized out>) at /usr/src/debug/wget2-2.0.0-2.fc36.x86_64/src/wget.c:219
#5  <signal handler called>
#6  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55a6e8bde2d8) at futex-internal.c:57
#7  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55a6e8bde2d8, expected=expected@entry=0, clockid=clockid@entry=0,
    abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#8  0x00007f10132ffa7f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55a6e8bde2d8, expected=expected@entry=0,
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#9  0x00007f1013302210 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55a6e8bde430, cond=0x55a6e8bde2b0) at pthread_cond_wait.c:503
#10 ___pthread_cond_wait (cond=0x55a6e8bde2b0, mutex=0x55a6e8bde430) at pthread_cond_wait.c:618
#11 0x00007f101358d125 in wget_thread_cond_wait (cond=<optimized out>, mutex=<optimized out>, ms=ms@entry=0)
    at /usr/src/debug/wget2-2.0.0-2.fc36.x86_64/libwget/thread.c:188
#12 0x000055a6e7cf2069 in main (argc=<optimized out>, argv=0x7ffda1c503b8) at /usr/src/debug/wget2-2.0.0-2.fc36.x86_64/src/wget.c:1409
```

**Comment by rockdaboot** [comment]
Thanks for reporting  This has been fixed in master and will be part of the next Bugfix release.

**Comment by remyabel2** [comment]
Got it. Found the commit. Thanks.
